tinymediamanager_service:
    image: xwtkdym/tinymediamanager:latest
    container_name: tinymediamanager
    ports:
      - "5800:5800"
      - "5900:5900"
    environment:
      - USER_ID=0
      - GROUP_ID=0
      - TZ=Europe/Madrid
      - VNC_PASSWORD=password
    volumes:
      - "./config:/config:rw"
      - "/opt/jellyfin/jellyfin/movies/:/media/movies"
      - "/opt/jellyfin/jellyfin/tvseries/:/media/tvseries"
